<?php
/**
 * Magento2 AddThis extension for share and follow buttons.
 * @package   Solutionexcel_AddThis
 * @author    SolutionExcel - https://www.solutionexcel.com/ - info@solutionexcel.com
 * @copyright Copyright © 2018 SolutionExcel. All rights reserved.
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License 3.0 | Open Source Initiative
**/
?>

<?php
if($block->isEnable()):
?>
	<div class="addthis_inline_follow_toolbox"></div>
<?php endif; ?>