<?php
/**
 * Magento2 AddThis extension for share and follow buttons.
 * @package   Solutionexcel_AddThis
 * @author    SolutionExcel - https://www.solutionexcel.com/ - info@solutionexcel.com
 * @copyright Copyright © 2018 SolutionExcel. All rights reserved.
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License 3.0 | Open Source Initiative
**/
?>

<?php
if($block->isEnable()):
	$pubId = $block->getPubId();
?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $pubId; ?>" async="async"></script>
<?php endif; ?>