<?php
/**
 * Magento2 AddThis extension for share and follow buttons.
 * @package   Solutionexcel_AddThis
 * @author    SolutionExcel - https://www.solutionexcel.com/ - info@solutionexcel.com
 * @copyright Copyright © 2018 SolutionExcel. All rights reserved.
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License 3.0 | Open Source Initiative
**/
?>

<?php if($block->isEnable()): ?>
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
  <a class="addthis_button_facebook"></a>
  <a class="addthis_button_twitter"></a>
  <a class="addthis_button_google_plusone_share"></a>
  <a class="addthis_button_linkedin"></a>
  <a class="addthis_button_email"></a>
  <a class="addthis_button_compact"></a>
  <a class="addthis_counter addthis_bubble_style"></a>
</div>
<?php endif; ?>